### PR TITLE
queryapp: fix build and query order

### PR DESCRIPTION
**Pull request by augiedoggie**

### CODE REVIEW

**Comment by waddlesplash** [comment]
Why does query order need to be changed?

**Comment by augiedoggie** [comment]
it's hinted at in the commit message...
`apparently queries in Haiku require 'name' to come first in the expression`

I have no idea why this is different from BeOS but it wouldn't work until I changed the order.

**Comment by waddlesplash** [comment]
This sounds like a bug in Haiku's query parsing/evaluation that should likely be reported and fixed.

**Comment by augiedoggie** [comment]
I have removed the change to the query order.  This and pull request #9 will build but obviously not work until the Haiku bug is fixed.

**Pull request merged**
